# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       procps-ng

# >> macros
# << macros

Summary:    System and process monitoring utilities
Version:    3.3.9
Release:    1
Group:      Applications/System
License:    GPL+ and GPLv2 and GPLv2+ and GPLv3+ and LGPLv2+
URL:        https://sourceforge.net/projects/procps-ng/
Source0:    %{name}-%{version}.tar.xz
Source100:  procps-ng.yaml
Patch0:     vmstat-wide-not-wide-enough.patch
Patch1:     ksh-skip-trailing-zeros.patch
Patch2:     vmstat-timestamps.patch
Patch3:     watch-fd-leak.patch
Patch4:     vmstat-format-security.patch
Patch5:     subtract-shmem-from-cached.patch
Patch6:     sysctl-linelen-signed.patch
Patch7:     ps-man-tracing.patch
Patch8:     revert-cached.patch
Requires:   systemd
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(ncurses)
BuildRequires:  pkgconfig(systemd)
BuildRequires:  libtool
BuildRequires:  automake
BuildRequires:  gettext-devel
Provides:   procps = %{version}-%{release}
Provides:   /sbin/sysctl
Provides:   /bin/ps
Provides:   /sbin/pidof
Obsoletes:   procps < 3.2.9

%description
The procps package contains a set of system utilities that provide
system information. Procps includes ps, free, skill, pkill, pgrep,
snice, tload, top, uptime, vmstat, w, watch and pwdx. The ps command
displays a snapshot of running processes. The top command provides
a repetitive update of the statuses of running processes. The free
command displays the amounts of free and used memory on your
system. The skill command sends a terminate command (or another
specified signal) to a specified set of processes. The snice
command is used to change the scheduling priority of specified
processes. The tload command prints a graph of the current system
load average to a specified tty. The uptime command displays the
current time, how long the system has been running, how many users
are logged on, and system load averages for the past one, five,
and fifteen minutes. The w command displays a list of the users
who are currently logged on and what they are running. The watch
program watches a running program. The vmstat command displays
virtual memory statistics about processes, memory, paging, block
I/O, traps, and CPU activity. The pwdx command reports the current
working directory of a process or processes.


%package devel
Summary:    System and process monitoring utilities
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Provides:   procps-devel = %{version}-%{release}
Obsoletes:  procps-devel < 3.2.9

%description devel
System and process monitoring utilities development headers.


%prep
%setup -q -n %{name}-%{version}/upstream

# vmstat-wide-not-wide-enough.patch
%patch0 -p1
# ksh-skip-trailing-zeros.patch
%patch1 -p1
# vmstat-timestamps.patch
%patch2 -p1
# watch-fd-leak.patch
%patch3 -p1
# vmstat-format-security.patch
%patch4 -p1
# subtract-shmem-from-cached.patch
%patch5 -p1
# sysctl-linelen-signed.patch
%patch6 -p1
# ps-man-tracing.patch
%patch7 -p1
# revert-cached.patch
%patch8 -p1
# >> setup
# << setup

%build
# >> build pre
NOCONFIGURE=1 ./autogen.sh
./configure --prefix=/ \
--bindir=%{_bindir} \
--sbindir=%{_sbindir} \
--libdir=%{_libdir} \
--mandir=%{_mandir} \
--includedir=%{_includedir} \
--sysconfdir=%{_sysconfdir} \
--docdir=/unwanted \
--disable-static \
--disable-w-from \
--disable-kill \
--enable-watch8bit \
--enable-skill \
--enable-sigwinch \
--with-systemd
# << build pre



# >> build post
make CFLAGS="%{optflags}"
# << build post

%install
rm -rf %{buildroot}
# >> install pre
make DESTDIR=%{buildroot} install
# << install pre

# >> install post
mkdir -p %{buildroot}%{_sysconfdir}/sysctl.d

ln -s %{_bindir}/pidof %{buildroot}%{_sbindir}/pidof
# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%doc AUTHORS Documentation/BUGS COPYING COPYING.LIB Documentation/FAQ NEWS README top/README.top Documentation/TODO
%{_libdir}/libprocps.so.*
%{_bindir}/*
%{_sbindir}/*
%{_sysconfdir}/sysctl.d
%{_mandir}/man1/*
%{_mandir}/man8/*
%{_mandir}/man5/*
%exclude %{_libdir}/libprocps.la
%exclude /unwanted/*
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%doc COPYING COPYING.LIB
%{_libdir}/libprocps.so
%{_libdir}/pkgconfig/libprocps.pc
%{_includedir}/proc
# >> files devel
# << files devel
